// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiGNnDxZQKOiIc3HYzfBW9jirc2lSBVrE',
    appId: '1:475699851165:web:8a5e92d44cecaa2efa4974',
    messagingSenderId: '475699851165',
    projectId: 'mysociety-693a7',
    authDomain: 'mysociety-693a7.firebaseapp.com',
    storageBucket: 'mysociety-693a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWrcFFEyZTK4S2CQc9hF1LM6C_g7JQvhk',
    appId: '1:475699851165:android:26de0a4b42b88433fa4974',
    messagingSenderId: '475699851165',
    projectId: 'mysociety-693a7',
    storageBucket: 'mysociety-693a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBokLJbZwfMaYXbL6vNrrZyFw3wSGw9hSo',
    appId: '1:475699851165:ios:995fcd9afda516bbfa4974',
    messagingSenderId: '475699851165',
    projectId: 'mysociety-693a7',
    storageBucket: 'mysociety-693a7.appspot.com',
    iosClientId: '475699851165-4cu8qj7voem4q405r98iakrm84ljjosv.apps.googleusercontent.com',
    iosBundleId: 'com.example.housingsociety',
  );
}
